### ISSUE TITLE
Question about Lab4 Part2

### ISSUE THREAD

**Issue by JessiicaWu** [cisc3620/4-3d-viewer#11]
I don't really understand the perspective projection. For glm::perspective, how can we determine the number for near and far. And also glm::ortho(left,right,bottom,top,near,far) what does these parameter represent, does it mean they are the coordinate of the model, also with near and far, how can we also determine these number, or can we set any number? 

Also, it said rotate the camera in the appropriate direction, do u mean it goes through the model and look back and the model will be just up side down. Thank you.

@rivlev

**Comment by rivlev** [comment]
You are determining what world coordinates should be displayed and which should be clipped out. For example, if your entire model is within the z range of [1, -10], your near value should be 1 and far should be -10. Remember to consider how your coordinates change after transformations.

I'm not sure I understand your second question, but see #6
