### ISSUE TITLE
2d to 3d

### ISSUE THREAD

**Issue by MichaelGregg** [cisc3620/4-3d-viewer#3]
To change a two dimensional triangle to 3d, it would go from three vertices (Top, Left, Right), to five vertices- Top (Ytop), LeftFront (Xleft, Ybottom, Znear), RightFront (Xright, Ybottom, Znear), LeftBack (Xleft, Ybottom, Zfar), and Rightback (Xright, Ybottom, Zfar). I can not figure out how to alter the vertex data accordingly, would the changes to do this occur in the "// Specify the layout of the vertex data" section of main?

**Comment by rivlev** [comment]
a triangle still has 3 vertices in 3d.
Do you mean coordinates? Instead of having two coordinates (x,y, with z set to 0 in the shader), it will have three (x, y, z). see #5

**Comment by MichaelGregg** [comment]
Thank you, i have already turned in the lab though, i should have closed this earlier
