### ISSUE TITLE
Rotate

### ISSUE THREAD

**Issue by J-A16** [cisc3620/4-3d-viewer#6]
How do you suggest we rotate the camera view?

@rivlev

**Comment by J-A16** [comment]
target - camera position = gaze vector, rotate gaze vector, then add new gaze vector with camera position tp get new target?

**Comment by J-A16** [comment]
This is really not clear, I don't know how these parameters are suppose to stick together.

**Comment by J-A16** [comment]
From rotate to forward and back, side to side, etc.

**Comment by rivlev** [comment]
When you rotate the camera horizontally, you are changing its *gaze* direction. When you rotate it vertically, you are changing its *up* direction. When you move it, you are changing its position.

**Comment by J-A16** [comment]
Can you give some example code, because it's actually a lot more complicated than that sounds

**Comment by rivlev** [comment]
the glm::lookat function(example on class slides) takes a position, up vector, and gaze vector. parameterize those arguments with global variables that will be  modified in the callback and recalculate and resend the camera matrix in the loop.

**Comment by J-A16** [comment]
It doesn't take a gaze vector, it takes a target position according to the slides.

**Comment by J-A16** [comment]
once we move, if we have the same target, it will rotate the camera too

**Comment by J-A16** [comment]
well, if we move sideways

**Comment by rivlev** [comment]
The gaze is the target position - camera position. 

Good point, you will have to modify the target as well to keep the gaze constant when you move the camera.

**Comment by J-A16** [comment]
So we target - position = gaze, rotate gaze, new gaze + position = new target? then when we move, add or subtract the same amount from the position and target?

**Comment by rivlev** [comment]
To rotate the gaze, you can just move the target (that's why I just called it gaze).
"then when we move, add or subtract the same amount from the position and target?"
exactly

**Comment by J-A16** [comment]
The up vector considers the camera position as it's origin?

**Comment by J-A16** [comment]
Sorry, wrong question

**Comment by J-A16** [comment]
The way I said to move the gaze sounds good right?

**Comment by J-A16** [comment]
if we change the up vector to rotate up and down, don't we have to change the target too?

**Comment by J-A16** [comment]
If it's suppose to be pointing to something and we change the up vector, what happens? It will stop looking at that thing and change it's true target location?

**Comment by J-A16** [comment]
I guess I can try it. What about to move left and right, get gaze vector, cross it by up vector and add or subtract the result to/from position? what if you rotate up until it is the same as gaze?

**Comment by J-A16** [comment]
Actually, it was a good question: the up vector uses the camera position as it's origin?

**Comment by rivlev** [comment]
you can work through the derivation. The simplest way to do it is what I said above.

The up vector has no origin or position, it just represents a direction.

**Comment by J-A16** [comment]
so, (0.0, 0.0, -1.0) would mean the camera is facing down?

**Comment by rivlev** [comment]
the third coordinate is z
it would face the negative z axis (into the screen)

**Comment by J-A16** [comment]
no, if it has a up axis of that. it still needs a target

**Comment by J-A16** [comment]
an up axis*

**Comment by J-A16** [comment]
so, an up axis of (0.0, 0.0, -1.0) with a target of origin would do what?

**Comment by rivlev** [comment]
The up axis is just a way to get the right axis.
The way the camera faces is determined by the gaze (or target).

Again, to rotate the camera move the target position vertically or horizontally.
To move the camera move both the camera and the target.

**Comment by J-A16** [comment]
Okay, so all rotation with the target? That sounds better.

**Comment by rivlev** [comment]
Yes. Please clean up this thread to just contain one question (with everything you think is relevant) and one answer (containing the information that answered your question) so it will be useful to others and then close.

**Comment by J-A16** [comment]
That sounds good. When it comes to the actual rotation, the lookat function accepts vec3s right? Do we create a new mat4(1.0f), rotate it, then take the gaze vec3, do gazeVec4 = rotateMat * vec4(gaze, 1.0f), then vec3(gazeVec4.x, gazeVec4.y, gazeVec4.z)?

**Comment by J-A16** [comment]
Also, we still have to rotate the up too when doing rotations up and down, right?

**Comment by J-A16** [comment]
Are these right?

**Comment by J-A16** [comment]
This is related to rotation: Should we print all three messages each time the camera is moved, or just whatever changed?

**Comment by rivlev** [comment]
Whatever changed.

**Comment by rivlev** [comment]
cleaned up so discussion will be useful for others
