### ISSUE TITLE
How to submit part 2 of Lab4

### ISSUE THREAD

**Issue by Mohamed-Alguhiem** [cisc3620/4-3d-viewer#7]
I already submitted lab4 part 1. I though a new repository will open for part 2 which I can then clone and submit part 2 through it. So how should I submit part 2 of lab 4. Do I just create a new branch called part2 and compare it with hw branch which has part1 or what.

**Comment by hlambrinoudis** [comment]
Unless we are told otherwise, I'd assume we would just make another commit on the same branch to master for submission. 
@rivlev

**Comment by rivlev** [comment]
No, there is no new repository. Make another pull request and make sure to @mention me.

(Also @mention me if you open an issue, otherwise I probably won't see it @Mohamed-Alguhiem )
