### ISSUE TITLE
Rotation Formula?

### ISSUE THREAD

**Issue by hlambrinoudis** [cisc3620/4-3d-viewer#9]
I was able to figure out how to move the camera left and right using by crossing cameraFront and cameraUp, and use the cameraFront to move forward and backwards, but I seem to be having some trouble figuring out a formula how to Rotate the camera.

@rivlev

**Comment by TarekCodes** [comment]
Try using glm::rotate, that should work for you.

**Comment by rivlev** [comment]
See #6
